spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev  #开发环境
  application:
    name: springcloud-config-client    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://euraka-dev.com:7001/eureka/ #只是测试切换结果
---
server:
  port: 8202
spring:
  profiles: test  #测试环境
  application:
    name: springcloud-config-client    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://euraka-test.com:7001/eureka/ #只是测试切换结果